'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var jsxRuntime = require('react/jsx-runtime');
var reactI18next = require('react-i18next');
require('@dynamic-labs/sdk-api');
require('../../../../shared/logger.cjs');
require('@dynamic-labs/iconic');
require('@dynamic-labs/wallet-connector-core');
require('../../../../context/ViewContext/ViewContext.cjs');
require('react');
var footerKeyIcon = require('../../../../shared/assets/footer-key-icon.cjs');
var userAccount2 = require('../../../../shared/assets/user-account-2.cjs');
require('@dynamic-labs/wallet-book');
require('../../../../utils/constants/colors.cjs');
require('../../../../shared/utils/classes/storage/localStorage.cjs');
require('viem');
require('@dynamic-labs/utils');
require('../../../../shared/consts/index.cjs');
require('../../../../context/DynamicContext/DynamicContext.cjs');
require('../../../../context/CaptchaContext/CaptchaContext.cjs');
require('../../../../context/ErrorContext/ErrorContext.cjs');
require('@dynamic-labs/multi-wallet');
require('../../../../context/AccessDeniedContext/AccessDeniedContext.cjs');
require('../../../../context/AccountExistsContext/AccountExistsContext.cjs');
require('../../../../config/ApiEndpoint.cjs');
require('../../../../context/EmailVerificationContext/EmailVerificationContext.cjs');
require('react-dom');
require('../../../../context/ThemeContext/ThemeContext.cjs');
require('@dynamic-labs/types');
require('yup');
require('../../../../context/MockContext/MockContext.cjs');
require('../../../../utils/hooks/useUserUpdateRequest/useUpdateUser/useUpdateUser.cjs');
require('../../../../context/UserFieldEditorContext/UserFieldEditorContext.cjs');
require('@dynamic-labs/rpc-providers');
require('../../../../context/UserWalletsContext/UserWalletsContext.cjs');
require('../../../../components/Transition/ZoomTransition/ZoomTransition.cjs');
require('../../../../components/Transition/SlideInUpTransition/SlideInUpTransition.cjs');
require('../../../../components/Transition/OpacityTransition/OpacityTransition.cjs');
require('../../../../components/ShadowDOM/ShadowDOM.cjs');
require('../../../../components/OverlayCard/OverlayCard.context.cjs');
require('../../../../context/FooterAnimationContext/index.cjs');
require('../../../../context/QrCodeContext/QrCodeContext.cjs');
var Typography = require('../../../../components/Typography/Typography.cjs');
require('../../../../context/WalletGroupContext/WalletGroupContext.cjs');
require('../../../../widgets/DynamicWidget/components/DynamicWidgetHeader/DynamicWidgetHeader.cjs');
require('qrcode');
require('../../../../context/LoadingContext/LoadingContext.cjs');
var Icon = require('../../../../components/Icon/Icon.cjs');
require('i18next');
require('../../../../widgets/DynamicWidget/context/DynamicWidgetContext.cjs');
require('../../../../components/UserProfile/parts/UserProfileField/components/VerifiedEmailIcon/VerifiedEmailIcon.cjs');
require('formik');
require('../../../../components/IconButton/IconButton.cjs');
require('../../../../components/Alert/Alert.cjs');
require('@dynamic-labs/viem-utils');
require('../../../../widgets/DynamicWidget/views/ManagePasskeysWidgetView/PasskeyCard/PasskeyCard.cjs');
var EnterTileAnimation = require('../../../../components/EnterTileAnimation/EnterTileAnimation.cjs');
require('../../../../components/InlineWidget/InlineWidget.cjs');
require('../../../../components/MenuList/Dropdown/Dropdown.cjs');
require('../../../../components/Popper/Popper/Popper.cjs');
require('../../../../components/Popper/PopperContext/PopperContext.cjs');
require('react-focus-lock');

const PasskeyInfoHelper = () => {
    const { t } = reactI18next.useTranslation();
    return (jsxRuntime.jsx("div", { className: 'passkey-info-help-content__container', children: jsxRuntime.jsx(EnterTileAnimation.EnterTileAnimation, { delay: '300ms', children: jsxRuntime.jsxs("div", { className: 'passkey-info-help-content__typography-wrapper', children: [jsxRuntime.jsxs("div", { className: 'passkey-info-help-content__details', children: [jsxRuntime.jsx(Icon.Icon, { size: 'medium', color: 'text-tertiary', children: jsxRuntime.jsx(userAccount2.ReactComponent, {}) }), jsxRuntime.jsxs("div", { className: 'passkey-info-help-content__wrapper', children: [jsxRuntime.jsx(Typography.Typography, { variant: 'title', weight: 'medium', copykey: 'dyn_passkey_intro.helper.section_1.title', children: t('dyn_passkey_intro.helper.section_1.title') }), jsxRuntime.jsx(Typography.Typography, { as: 'p', variant: 'body_normal', weight: 'regular', color: 'secondary', className: 'passkey-info-help-content__typography--label', copykey: 'dyn_passkey_intro.helper.section_1.description', children: t('dyn_passkey_intro.helper.section_1.description') })] })] }), jsxRuntime.jsxs("div", { className: 'passkey-info-help-content__details', children: [jsxRuntime.jsx(Icon.Icon, { size: 'medium', color: 'text-tertiary', children: jsxRuntime.jsx(footerKeyIcon.ReactComponent, {}) }), jsxRuntime.jsxs("div", { className: 'passkey-info-help-content__wrapper', children: [jsxRuntime.jsx(Typography.Typography, { variant: 'title', weight: 'medium', copykey: 'dyn_passkey_intro.helper.section_2.title', children: t('dyn_passkey_intro.helper.section_2.title') }), jsxRuntime.jsx(Typography.Typography, { as: 'p', variant: 'body_normal', weight: 'regular', color: 'secondary', className: 'passkey-info-help-content__typography--label', copykey: 'dyn_passkey_intro.helper.section_2.description', children: t('dyn_passkey_intro.helper.section_2.description') })] })] })] }) }) }));
};

exports.PasskeyInfoHelper = PasskeyInfoHelper;
