/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum AccessOutcomeEnum {
    Scope = "scope",
    SiteAccess = "siteAccess"
}
export declare function AccessOutcomeEnumFromJSON(json: any): AccessOutcomeEnum;
export declare function AccessOutcomeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessOutcomeEnum;
export declare function AccessOutcomeEnumToJSON(value?: AccessOutcomeEnum | null): any;
