'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
exports.AccessOutcomeEnum = void 0;
(function (AccessOutcomeEnum) {
    AccessOutcomeEnum["Scope"] = "scope";
    AccessOutcomeEnum["SiteAccess"] = "siteAccess";
})(exports.AccessOutcomeEnum || (exports.AccessOutcomeEnum = {}));
function AccessOutcomeEnumFromJSON(json) {
    return AccessOutcomeEnumFromJSONTyped(json);
}
function AccessOutcomeEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function AccessOutcomeEnumToJSON(value) {
    return value;
}

exports.AccessOutcomeEnumFromJSON = AccessOutcomeEnumFromJSON;
exports.AccessOutcomeEnumFromJSONTyped = AccessOutcomeEnumFromJSONTyped;
exports.AccessOutcomeEnumToJSON = AccessOutcomeEnumToJSON;
