/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccessOutcomeEnum } from './AccessOutcomeEnum';
/**
 *
 * @export
 * @interface Allowlist
 */
export interface Allowlist {
    /**
     *
     * @type {string}
     * @memberof Allowlist
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof Allowlist
     */
    name: string;
    /**
     *
     * @type {Date}
     * @memberof Allowlist
     */
    enabledAt?: Date | null;
    /**
     *
     * @type {string}
     * @memberof Allowlist
     */
    projectEnvironmentId: string;
    /**
     *
     * @type {string}
     * @memberof Allowlist
     */
    scope?: string | null;
    /**
     *
     * @type {AccessOutcomeEnum}
     * @memberof Allowlist
     */
    outcome?: AccessOutcomeEnum;
}
export declare function AllowlistFromJSON(json: any): Allowlist;
export declare function AllowlistFromJSONTyped(json: any, ignoreDiscriminator: boolean): Allowlist;
export declare function AllowlistToJSON(value?: Allowlist | null): any;
