/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AllowlistEntry } from './AllowlistEntry';
/**
 *
 * @export
 * @interface AllowlistEntriesResponse
 */
export interface AllowlistEntriesResponse {
    /**
     *
     * @type {number}
     * @memberof AllowlistEntriesResponse
     */
    count?: number;
    /**
     *
     * @type {Array<AllowlistEntry>}
     * @memberof AllowlistEntriesResponse
     */
    entries?: Array<AllowlistEntry>;
}
export declare function AllowlistEntriesResponseFromJSON(json: any): AllowlistEntriesResponse;
export declare function AllowlistEntriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllowlistEntriesResponse;
export declare function AllowlistEntriesResponseToJSON(value?: AllowlistEntriesResponse | null): any;
