/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AnalyticsSessionsByDateSessions
 */
export interface AnalyticsSessionsByDateSessions {
    /**
     *
     * @type {number}
     * @memberof AnalyticsSessionsByDateSessions
     */
    count?: number;
    /**
     *
     * @type {string}
     * @memberof AnalyticsSessionsByDateSessions
     */
    date?: string;
}
export declare function AnalyticsSessionsByDateSessionsFromJSON(json: any): AnalyticsSessionsByDateSessions;
export declare function AnalyticsSessionsByDateSessionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsSessionsByDateSessions;
export declare function AnalyticsSessionsByDateSessionsToJSON(value?: AnalyticsSessionsByDateSessions | null): any;
