/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnalyticsSessionsByDate } from './AnalyticsSessionsByDate';
/**
 *
 * @export
 * @interface AnalyticsVisitResponse
 */
export interface AnalyticsVisitResponse {
    /**
     *
     * @type {number}
     * @memberof AnalyticsVisitResponse
     */
    summedSessionsCount?: number;
    /**
     *
     * @type {number}
     * @memberof AnalyticsVisitResponse
     */
    summedTotalUniqueCount?: number;
    /**
     *
     * @type {AnalyticsSessionsByDate}
     * @memberof AnalyticsVisitResponse
     */
    users?: AnalyticsSessionsByDate;
    /**
     *
     * @type {AnalyticsSessionsByDate}
     * @memberof AnalyticsVisitResponse
     */
    visits?: AnalyticsSessionsByDate;
}
export declare function AnalyticsVisitResponseFromJSON(json: any): AnalyticsVisitResponse;
export declare function AnalyticsVisitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsVisitResponse;
export declare function AnalyticsVisitResponseToJSON(value?: AnalyticsVisitResponse | null): any;
