/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AnalyticsSessionsByDateSessions } from './AnalyticsSessionsByDateSessions';
/**
 *
 * @export
 * @interface AnalyticsSessionsByDate
 */
export interface AnalyticsSessionsByDate {
    /**
     *
     * @type {number}
     * @memberof AnalyticsSessionsByDate
     */
    totalUnique?: number;
    /**
     *
     * @type {Array<AnalyticsSessionsByDateSessions>}
     * @memberof AnalyticsSessionsByDate
     */
    sessions?: Array<AnalyticsSessionsByDateSessions>;
}
export declare function AnalyticsSessionsByDateFromJSON(json: any): AnalyticsSessionsByDate;
export declare function AnalyticsSessionsByDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsSessionsByDate;
export declare function AnalyticsSessionsByDateToJSON(value?: AnalyticsSessionsByDate | null): any;
