'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
exports.BillingSubscriptionPlanTypeEnum = void 0;
(function (BillingSubscriptionPlanTypeEnum) {
    BillingSubscriptionPlanTypeEnum["Free"] = "free";
    BillingSubscriptionPlanTypeEnum["Advanced"] = "advanced";
    BillingSubscriptionPlanTypeEnum["Enterprise"] = "enterprise";
})(exports.BillingSubscriptionPlanTypeEnum || (exports.BillingSubscriptionPlanTypeEnum = {}));
function BillingSubscriptionPlanTypeEnumFromJSON(json) {
    return BillingSubscriptionPlanTypeEnumFromJSONTyped(json);
}
function BillingSubscriptionPlanTypeEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function BillingSubscriptionPlanTypeEnumToJSON(value) {
    return value;
}

exports.BillingSubscriptionPlanTypeEnumFromJSON = BillingSubscriptionPlanTypeEnumFromJSON;
exports.BillingSubscriptionPlanTypeEnumFromJSONTyped = BillingSubscriptionPlanTypeEnumFromJSONTyped;
exports.BillingSubscriptionPlanTypeEnumToJSON = BillingSubscriptionPlanTypeEnumToJSON;
