/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum BillingSubscriptionPlanTypeEnum {
    Free = "free",
    Advanced = "advanced",
    Enterprise = "enterprise"
}
export declare function BillingSubscriptionPlanTypeEnumFromJSON(json: any): BillingSubscriptionPlanTypeEnum;
export declare function BillingSubscriptionPlanTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingSubscriptionPlanTypeEnum;
export declare function BillingSubscriptionPlanTypeEnumToJSON(value?: BillingSubscriptionPlanTypeEnum | null): any;
