/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ChainalysisConfiguration
 */
export interface ChainalysisConfiguration {
    /**
     *
     * @type {string}
     * @memberof ChainalysisConfiguration
     */
    id: string;
    /**
     *
     * @type {boolean}
     * @memberof ChainalysisConfiguration
     */
    sanctionsApiEnabled: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ChainalysisConfiguration
     */
    kytApiEnabled: boolean;
    /**
     *
     * @type {string}
     * @memberof ChainalysisConfiguration
     */
    projectEnvironmentId: string;
    /**
     *
     * @type {Date}
     * @memberof ChainalysisConfiguration
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof ChainalysisConfiguration
     */
    updatedAt: Date;
}
export declare function ChainalysisConfigurationFromJSON(json: any): ChainalysisConfiguration;
export declare function ChainalysisConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainalysisConfiguration;
export declare function ChainalysisConfigurationToJSON(value?: ChainalysisConfiguration | null): any;
