/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum ChainalysisCheckResultEnum {
    Ok = "OK",
    Blocked = "BLOCKED",
    Failed = "FAILED"
}
export declare function ChainalysisCheckResultEnumFromJSON(json: any): ChainalysisCheckResultEnum;
export declare function ChainalysisCheckResultEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainalysisCheckResultEnum;
export declare function ChainalysisCheckResultEnumToJSON(value?: ChainalysisCheckResultEnum | null): any;
