/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TokenAddress } from './TokenAddress';
/**
 * Defined an one token which can have multiple contract addresses dependent to networkId
 * @export
 * @interface ChainToken
 */
export interface ChainToken {
    /**
     * Name of the token
     * @type {string}
     * @memberof ChainToken
     */
    name: string;
    /**
     * Symbol of the token
     * @type {string}
     * @memberof ChainToken
     */
    symbol: string;
    /**
     * Array of different contract addresses dependent to networkId
     * @type {Array<TokenAddress>}
     * @memberof ChainToken
     */
    tokenAddresses: Array<TokenAddress>;
}
export declare function ChainTokenFromJSON(json: any): ChainToken;
export declare function ChainTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainToken;
export declare function ChainTokenToJSON(value?: ChainToken | null): any;
