/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChainalysisCheckResultEnum } from './ChainalysisCheckResultEnum';
/**
 *
 * @export
 * @interface ChainalysisCheck
 */
export interface ChainalysisCheck {
    /**
     *
     * @type {string}
     * @memberof ChainalysisCheck
     */
    id: string;
    /**
     *
     * @type {Date}
     * @memberof ChainalysisCheck
     */
    createdAt: Date;
    /**
     *
     * @type {ChainalysisCheckResultEnum}
     * @memberof ChainalysisCheck
     */
    result: ChainalysisCheckResultEnum;
    /**
     * Valid blockchain wallet address, must be an alphanumeric string without any special characters
     * @type {string}
     * @memberof ChainalysisCheck
     */
    walletPublicKey: string;
    /**
     *
     * @type {string}
     * @memberof ChainalysisCheck
     */
    response: string;
}
export declare function ChainalysisCheckFromJSON(json: any): ChainalysisCheck;
export declare function ChainalysisCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainalysisCheck;
export declare function ChainalysisCheckToJSON(value?: ChainalysisCheck | null): any;
