'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
exports.ChainalysisCheckResultEnum = void 0;
(function (ChainalysisCheckResultEnum) {
    ChainalysisCheckResultEnum["Ok"] = "OK";
    ChainalysisCheckResultEnum["Blocked"] = "BLOCKED";
    ChainalysisCheckResultEnum["Failed"] = "FAILED";
})(exports.ChainalysisCheckResultEnum || (exports.ChainalysisCheckResultEnum = {}));
function ChainalysisCheckResultEnumFromJSON(json) {
    return ChainalysisCheckResultEnumFromJSONTyped(json);
}
function ChainalysisCheckResultEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function ChainalysisCheckResultEnumToJSON(value) {
    return value;
}

exports.ChainalysisCheckResultEnumFromJSON = ChainalysisCheckResultEnumFromJSON;
exports.ChainalysisCheckResultEnumFromJSONTyped = ChainalysisCheckResultEnumFromJSONTyped;
exports.ChainalysisCheckResultEnumToJSON = ChainalysisCheckResultEnumToJSON;
