/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateProjectResponseProject } from './CreateProjectResponseProject';
/**
 *
 * @export
 * @interface CreateProjectResponse
 */
export interface CreateProjectResponse {
    /**
     *
     * @type {CreateProjectResponseProject}
     * @memberof CreateProjectResponse
     */
    project?: CreateProjectResponseProject;
}
export declare function CreateProjectResponseFromJSON(json: any): CreateProjectResponse;
export declare function CreateProjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectResponse;
export declare function CreateProjectResponseToJSON(value?: CreateProjectResponse | null): any;
