/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChainEnum } from './ChainEnum';
import { UserIdentifierTypeEnum } from './UserIdentifierTypeEnum';
/**
 *
 * @export
 * @interface CreateUserEmbeddedWalletsRequest
 */
export interface CreateUserEmbeddedWalletsRequest {
    /**
     * Identifier for the user. Must be either an email or user id.
     * @type {string}
     * @memberof CreateUserEmbeddedWalletsRequest
     */
    identifier: string;
    /**
     *
     * @type {UserIdentifierTypeEnum}
     * @memberof CreateUserEmbeddedWalletsRequest
     */
    type: UserIdentifierTypeEnum;
    /**
     *
     * @type {ChainEnum}
     * @memberof CreateUserEmbeddedWalletsRequest
     */
    chain: ChainEnum;
}
export declare function CreateUserEmbeddedWalletsRequestFromJSON(json: any): CreateUserEmbeddedWalletsRequest;
export declare function CreateUserEmbeddedWalletsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserEmbeddedWalletsRequest;
export declare function CreateUserEmbeddedWalletsRequestToJSON(value?: CreateUserEmbeddedWalletsRequest | null): any;
