/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CreateProjectResponseProjectProjectEnvironments
 */
export interface CreateProjectResponseProjectProjectEnvironments {
    /**
     *
     * @type {string}
     * @memberof CreateProjectResponseProjectProjectEnvironments
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof CreateProjectResponseProjectProjectEnvironments
     */
    environmentName?: string;
}
export declare function CreateProjectResponseProjectProjectEnvironmentsFromJSON(json: any): CreateProjectResponseProjectProjectEnvironments;
export declare function CreateProjectResponseProjectProjectEnvironmentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectResponseProjectProjectEnvironments;
export declare function CreateProjectResponseProjectProjectEnvironmentsToJSON(value?: CreateProjectResponseProjectProjectEnvironments | null): any;
