/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateProjectResponseProjectProjectEnvironments } from './CreateProjectResponseProjectProjectEnvironments';
/**
 *
 * @export
 * @interface CreateProjectResponseProject
 */
export interface CreateProjectResponseProject {
    /**
     *
     * @type {string}
     * @memberof CreateProjectResponseProject
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof CreateProjectResponseProject
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof CreateProjectResponseProject
     */
    organizationId?: string;
    /**
     *
     * @type {Array<CreateProjectResponseProjectProjectEnvironments>}
     * @memberof CreateProjectResponseProject
     */
    projectEnvironments?: Array<CreateProjectResponseProjectProjectEnvironments>;
}
export declare function CreateProjectResponseProjectFromJSON(json: any): CreateProjectResponseProject;
export declare function CreateProjectResponseProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectResponseProject;
export declare function CreateProjectResponseProjectToJSON(value?: CreateProjectResponseProject | null): any;
