/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface EmbeddedWalletExportResponse
 */
export interface EmbeddedWalletExportResponse {
    /**
     *
     * @type {object}
     * @memberof EmbeddedWalletExportResponse
     */
    exportBundle: object;
}
export declare function EmbeddedWalletExportResponseFromJSON(json: any): EmbeddedWalletExportResponse;
export declare function EmbeddedWalletExportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddedWalletExportResponse;
export declare function EmbeddedWalletExportResponseToJSON(value?: EmbeddedWalletExportResponse | null): any;
