/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface EmbeddedWalletExportRequest
 */
export interface EmbeddedWalletExportRequest {
    /**
     * The public key of the wallet that will be used to encrypt the exported wallet.
     * @type {string}
     * @memberof EmbeddedWalletExportRequest
     */
    targetPublicKey: string;
}
export declare function EmbeddedWalletExportRequestFromJSON(json: any): EmbeddedWalletExportRequest;
export declare function EmbeddedWalletExportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddedWalletExportRequest;
export declare function EmbeddedWalletExportRequestToJSON(value?: EmbeddedWalletExportRequest | null): any;
