/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnvironmentVisitorsResponseUsers } from './EnvironmentVisitorsResponseUsers';
/**
 *
 * @export
 * @interface EnvironmentVisitorsResponse
 */
export interface EnvironmentVisitorsResponse {
    /**
     *
     * @type {EnvironmentVisitorsResponseUsers}
     * @memberof EnvironmentVisitorsResponse
     */
    users?: EnvironmentVisitorsResponseUsers;
    /**
     *
     * @type {EnvironmentVisitorsResponseUsers}
     * @memberof EnvironmentVisitorsResponse
     */
    visitors?: EnvironmentVisitorsResponseUsers;
}
export declare function EnvironmentVisitorsResponseFromJSON(json: any): EnvironmentVisitorsResponse;
export declare function EnvironmentVisitorsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnvironmentVisitorsResponse;
export declare function EnvironmentVisitorsResponseToJSON(value?: EnvironmentVisitorsResponse | null): any;
