/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface EnvironmentVisitorsResponseUsers
 */
export interface EnvironmentVisitorsResponseUsers {
    /**
     *
     * @type {number}
     * @memberof EnvironmentVisitorsResponseUsers
     */
    count?: number;
}
export declare function EnvironmentVisitorsResponseUsersFromJSON(json: any): EnvironmentVisitorsResponseUsers;
export declare function EnvironmentVisitorsResponseUsersFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnvironmentVisitorsResponseUsers;
export declare function EnvironmentVisitorsResponseUsersToJSON(value?: EnvironmentVisitorsResponseUsers | null): any;
