/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnvironmentEnum } from './EnvironmentEnum';
/**
 *
 * @export
 * @interface Event
 */
export interface Event {
    /**
     *
     * @type {string}
     * @memberof Event
     */
    eventId: string;
    /**
     *
     * @type {string}
     * @memberof Event
     */
    environmentId: string;
    /**
     *
     * @type {EnvironmentEnum}
     * @memberof Event
     */
    environmentName: EnvironmentEnum;
    /**
     *
     * @type {string}
     * @memberof Event
     */
    eventAction?: string;
    /**
     *
     * @type {string}
     * @memberof Event
     */
    eventName: string;
    /**
     *
     * @type {string}
     * @memberof Event
     */
    resourceType?: string;
    /**
     *
     * @type {Date}
     * @memberof Event
     */
    timestamp: Date;
    /**
     *
     * @type {object}
     * @memberof Event
     */
    data: object;
}
export declare function EventFromJSON(json: any): Event;
export declare function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event;
export declare function EventToJSON(value?: Event | null): any;
