/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface EventType
 */
export interface EventType {
    /**
     *
     * @type {string}
     * @memberof EventType
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof EventType
     */
    description: string;
}
export declare function EventTypeFromJSON(json: any): EventType;
export declare function EventTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventType;
export declare function EventTypeToJSON(value?: EventType | null): any;
