/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Export } from './Export';
/**
 *
 * @export
 * @interface ExportsResponse
 */
export interface ExportsResponse {
    /**
     *
     * @type {Array<Export>}
     * @memberof ExportsResponse
     */
    exports?: Array<Export>;
}
export declare function ExportsResponseFromJSON(json: any): ExportsResponse;
export declare function ExportsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportsResponse;
export declare function ExportsResponseToJSON(value?: ExportsResponse | null): any;
