'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
exports.ExportStatusEnum = void 0;
(function (ExportStatusEnum) {
    ExportStatusEnum["Completed"] = "completed";
    ExportStatusEnum["Failed"] = "failed";
    ExportStatusEnum["Pending"] = "pending";
})(exports.ExportStatusEnum || (exports.ExportStatusEnum = {}));
function ExportStatusEnumFromJSON(json) {
    return ExportStatusEnumFromJSONTyped(json);
}
function ExportStatusEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function ExportStatusEnumToJSON(value) {
    return value;
}

exports.ExportStatusEnumFromJSON = ExportStatusEnumFromJSON;
exports.ExportStatusEnumFromJSONTyped = ExportStatusEnumFromJSONTyped;
exports.ExportStatusEnumToJSON = ExportStatusEnumToJSON;
