/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum ExportModelEnum {
    Users = "users"
}
export declare function ExportModelEnumFromJSON(json: any): ExportModelEnum;
export declare function ExportModelEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportModelEnum;
export declare function ExportModelEnumToJSON(value?: ExportModelEnum | null): any;
