/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserSearchFilterParams } from './UserSearchFilterParams';
/**
 *
 * @export
 * @interface ExportCreateRequestFilter
 */
export interface ExportCreateRequestFilter {
    /**
     *
     * @type {UserSearchFilterParams}
     * @memberof ExportCreateRequestFilter
     */
    users?: UserSearchFilterParams;
}
export declare function ExportCreateRequestFilterFromJSON(json: any): ExportCreateRequestFilter;
export declare function ExportCreateRequestFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportCreateRequestFilter;
export declare function ExportCreateRequestFilterToJSON(value?: ExportCreateRequestFilter | null): any;
