/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
var ExportFormatEnum;
(function (ExportFormatEnum) {
    ExportFormatEnum["Csv"] = "csv";
})(ExportFormatEnum || (ExportFormatEnum = {}));
function ExportFormatEnumFromJSON(json) {
    return ExportFormatEnumFromJSONTyped(json);
}
function ExportFormatEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function ExportFormatEnumToJSON(value) {
    return value;
}

export { ExportFormatEnum, ExportFormatEnumFromJSON, ExportFormatEnumFromJSONTyped, ExportFormatEnumToJSON };
