/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExportCreateRequestFilter } from './ExportCreateRequestFilter';
import { ExportFormatEnum } from './ExportFormatEnum';
import { ExportModelEnum } from './ExportModelEnum';
/**
 * Request body to create a new export.
 * @export
 * @interface ExportCreateRequest
 */
export interface ExportCreateRequest {
    /**
     *
     * @type {ExportFormatEnum}
     * @memberof ExportCreateRequest
     */
    format: ExportFormatEnum;
    /**
     *
     * @type {ExportModelEnum}
     * @memberof ExportCreateRequest
     */
    model: ExportModelEnum;
    /**
     *
     * @type {ExportCreateRequestFilter}
     * @memberof ExportCreateRequest
     */
    filter?: ExportCreateRequestFilter;
}
export declare function ExportCreateRequestFromJSON(json: any): ExportCreateRequest;
export declare function ExportCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportCreateRequest;
export declare function ExportCreateRequestToJSON(value?: ExportCreateRequest | null): any;
