'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
exports.ExportFormatEnum = void 0;
(function (ExportFormatEnum) {
    ExportFormatEnum["Csv"] = "csv";
})(exports.ExportFormatEnum || (exports.ExportFormatEnum = {}));
function ExportFormatEnumFromJSON(json) {
    return ExportFormatEnumFromJSONTyped(json);
}
function ExportFormatEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function ExportFormatEnumToJSON(value) {
    return value;
}

exports.ExportFormatEnumFromJSON = ExportFormatEnumFromJSON;
exports.ExportFormatEnumFromJSONTyped = ExportFormatEnumFromJSONTyped;
exports.ExportFormatEnumToJSON = ExportFormatEnumToJSON;
