'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
exports.GateRuleType = void 0;
(function (GateRuleType) {
    GateRuleType["Nft"] = "nft";
    GateRuleType["Token"] = "token";
})(exports.GateRuleType || (exports.GateRuleType = {}));
function GateRuleTypeFromJSON(json) {
    return GateRuleTypeFromJSONTyped(json);
}
function GateRuleTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function GateRuleTypeToJSON(value) {
    return value;
}

exports.GateRuleTypeFromJSON = GateRuleTypeFromJSON;
exports.GateRuleTypeFromJSONTyped = GateRuleTypeFromJSONTyped;
exports.GateRuleTypeToJSON = GateRuleTypeToJSON;
