/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Gate } from './Gate';
/**
 *
 * @export
 * @interface GatesResponse
 */
export interface GatesResponse {
    /**
     *
     * @type {Array<Gate>}
     * @memberof GatesResponse
     */
    gates?: Array<Gate>;
}
export declare function GatesResponseFromJSON(json: any): GatesResponse;
export declare function GatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatesResponse;
export declare function GatesResponseToJSON(value?: GatesResponse | null): any;
