/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum GateRuleType {
    Nft = "nft",
    Token = "token"
}
export declare function GateRuleTypeFromJSON(json: any): GateRuleType;
export declare function GateRuleTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GateRuleType;
export declare function GateRuleTypeToJSON(value?: GateRuleType | null): any;
