/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * An [RFC 6454](https://www.rfc-editor.org/rfc/rfc6454) valid url. Must not include any paths. A single wildcard (*) can be used as the first subdomain.
     * @type {string}
     * @memberof InlineObject
     */
    origin: string;
}
export declare function InlineObjectFromJSON(json: any): InlineObject;
export declare function InlineObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject;
export declare function InlineObjectToJSON(value?: InlineObject | null): any;
