/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OriginResponse } from './OriginResponse';
/**
 *
 * @export
 * @interface InlineResponse201
 */
export interface InlineResponse201 {
    /**
     *
     * @type {OriginResponse}
     * @memberof InlineResponse201
     */
    origin?: OriginResponse;
}
export declare function InlineResponse201FromJSON(json: any): InlineResponse201;
export declare function InlineResponse201FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse201;
export declare function InlineResponse201ToJSON(value?: InlineResponse201 | null): any;
