/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface InlineResponse400
 */
export interface InlineResponse400 {
    /**
     *
     * @type {string}
     * @memberof InlineResponse400
     */
    error?: string;
    /**
     *
     * @type {number}
     * @memberof InlineResponse400
     */
    status?: number;
}
export declare function InlineResponse400FromJSON(json: any): InlineResponse400;
export declare function InlineResponse400FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse400;
export declare function InlineResponse400ToJSON(value?: InlineResponse400 | null): any;
