/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface InternalUserFieldsAllOf
 */
export interface InternalUserFieldsAllOf {
    /**
     *
     * @type {object}
     * @memberof InternalUserFieldsAllOf
     */
    metadata?: object;
}
export declare function InternalUserFieldsAllOfFromJSON(json: any): InternalUserFieldsAllOf;
export declare function InternalUserFieldsAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalUserFieldsAllOf;
export declare function InternalUserFieldsAllOfToJSON(value?: InternalUserFieldsAllOf | null): any;
