'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
exports.InviteStatusEnum = void 0;
(function (InviteStatusEnum) {
    InviteStatusEnum["Pending"] = "pending";
    InviteStatusEnum["Rejected"] = "rejected";
    InviteStatusEnum["Accepted"] = "accepted";
})(exports.InviteStatusEnum || (exports.InviteStatusEnum = {}));
function InviteStatusEnumFromJSON(json) {
    return InviteStatusEnumFromJSONTyped(json);
}
function InviteStatusEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function InviteStatusEnumToJSON(value) {
    return value;
}

exports.InviteStatusEnumFromJSON = InviteStatusEnumFromJSON;
exports.InviteStatusEnumFromJSONTyped = InviteStatusEnumFromJSONTyped;
exports.InviteStatusEnumToJSON = InviteStatusEnumToJSON;
