/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InviteStatusEnum } from './InviteStatusEnum';
/**
 *
 * @export
 * @interface Invite
 */
export interface Invite {
    /**
     *
     * @type {string}
     * @memberof Invite
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof Invite
     */
    organizationId: string;
    /**
     *
     * @type {string}
     * @memberof Invite
     */
    organizationName: string;
    /**
     *
     * @type {InviteStatusEnum}
     * @memberof Invite
     */
    status: InviteStatusEnum;
    /**
     *
     * @type {string}
     * @memberof Invite
     */
    email?: string;
    /**
     *
     * @type {string}
     * @memberof Invite
     */
    alias?: string;
    /**
     *
     * @type {string}
     * @memberof Invite
     */
    walletPublicKey?: string;
}
export declare function InviteFromJSON(json: any): Invite;
export declare function InviteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Invite;
export declare function InviteToJSON(value?: Invite | null): any;
