/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InviteStatusEnum } from './InviteStatusEnum';
/**
 *
 * @export
 * @interface InviteUpdateRequest
 */
export interface InviteUpdateRequest {
    /**
     *
     * @type {InviteStatusEnum}
     * @memberof InviteUpdateRequest
     */
    status: InviteStatusEnum;
}
export declare function InviteUpdateRequestFromJSON(json: any): InviteUpdateRequest;
export declare function InviteUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteUpdateRequest;
export declare function InviteUpdateRequestToJSON(value?: InviteUpdateRequest | null): any;
