/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum InviteStatusEnum {
    Pending = "pending",
    Rejected = "rejected",
    Accepted = "accepted"
}
export declare function InviteStatusEnumFromJSON(json: any): InviteStatusEnum;
export declare function InviteStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteStatusEnum;
export declare function InviteStatusEnumToJSON(value?: InviteStatusEnum | null): any;
