/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface InviteConflictResponse
 */
export interface InviteConflictResponse {
    /**
     *
     * @type {string}
     * @memberof InviteConflictResponse
     */
    message?: string;
}
export declare function InviteConflictResponseFromJSON(json: any): InviteConflictResponse;
export declare function InviteConflictResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteConflictResponse;
export declare function InviteConflictResponseToJSON(value?: InviteConflictResponse | null): any;
