/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Key
 */
export interface Key {
    /**
     *
     * @type {string}
     * @memberof Key
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof Key
     */
    publicKey?: string;
}
export declare function KeyFromJSON(json: any): Key;
export declare function KeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Key;
export declare function KeyToJSON(value?: Key | null): any;
