/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Key } from './Key';
/**
 *
 * @export
 * @interface KeyResponse
 */
export interface KeyResponse {
    /**
     *
     * @type {Key}
     * @memberof KeyResponse
     */
    key?: Key;
}
export declare function KeyResponseFromJSON(json: any): KeyResponse;
export declare function KeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyResponse;
export declare function KeyResponseToJSON(value?: KeyResponse | null): any;
