/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface NextSettings
 */
export interface NextSettings {
    /**
     *
     * @type {string}
     * @memberof NextSettings
     */
    version?: string;
}
export declare function NextSettingsFromJSON(json: any): NextSettings;
export declare function NextSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NextSettings;
export declare function NextSettingsToJSON(value?: NextSettings | null): any;
