/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './User';
/**
 *
 * @export
 * @interface OrganizationMember
 */
export interface OrganizationMember {
    /**
     *
     * @type {string}
     * @memberof OrganizationMember
     */
    id: string;
    /**
     *
     * @type {User}
     * @memberof OrganizationMember
     */
    user: User;
}
export declare function OrganizationMemberFromJSON(json: any): OrganizationMember;
export declare function OrganizationMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationMember;
export declare function OrganizationMemberToJSON(value?: OrganizationMember | null): any;
