/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganizationResponseOrganization } from './OrganizationResponseOrganization';
/**
 *
 * @export
 * @interface OrganizationResponse
 */
export interface OrganizationResponse {
    /**
     *
     * @type {OrganizationResponseOrganization}
     * @memberof OrganizationResponse
     */
    organization?: OrganizationResponseOrganization;
}
export declare function OrganizationResponseFromJSON(json: any): OrganizationResponse;
export declare function OrganizationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationResponse;
export declare function OrganizationResponseToJSON(value?: OrganizationResponse | null): any;
