/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WhenToImplementEnum } from './WhenToImplementEnum';
/**
 *
 * @export
 * @interface OrganizationRequest
 */
export interface OrganizationRequest {
    /**
     *
     * @type {string}
     * @memberof OrganizationRequest
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof OrganizationRequest
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof OrganizationRequest
     */
    websiteUrl?: string;
    /**
     *
     * @type {WhenToImplementEnum}
     * @memberof OrganizationRequest
     */
    implementationTimeline?: WhenToImplementEnum;
}
export declare function OrganizationRequestFromJSON(json: any): OrganizationRequest;
export declare function OrganizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationRequest;
export declare function OrganizationRequestToJSON(value?: OrganizationRequest | null): any;
