/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganizationMember } from './OrganizationMember';
/**
 *
 * @export
 * @interface OrganizationMembersResponse
 */
export interface OrganizationMembersResponse {
    /**
     *
     * @type {number}
     * @memberof OrganizationMembersResponse
     */
    count: number;
    /**
     *
     * @type {Array<OrganizationMember>}
     * @memberof OrganizationMembersResponse
     */
    members: Array<OrganizationMember>;
}
export declare function OrganizationMembersResponseFromJSON(json: any): OrganizationMembersResponse;
export declare function OrganizationMembersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationMembersResponse;
export declare function OrganizationMembersResponseToJSON(value?: OrganizationMembersResponse | null): any;
