/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Organization
 */
export interface Organization {
    /**
     *
     * @type {string}
     * @memberof Organization
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof Organization
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof Organization
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof Organization
     */
    websiteUrl?: string;
}
export declare function OrganizationFromJSON(json: any): Organization;
export declare function OrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Organization;
export declare function OrganizationToJSON(value?: Organization | null): any;
