/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OrganizationResponseOrganization
 */
export interface OrganizationResponseOrganization {
    /**
     *
     * @type {string}
     * @memberof OrganizationResponseOrganization
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof OrganizationResponseOrganization
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof OrganizationResponseOrganization
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof OrganizationResponseOrganization
     */
    websiteUrl?: string;
}
export declare function OrganizationResponseOrganizationFromJSON(json: any): OrganizationResponseOrganization;
export declare function OrganizationResponseOrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationResponseOrganization;
export declare function OrganizationResponseOrganizationToJSON(value?: OrganizationResponseOrganization | null): any;
