/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OriginResponse } from './OriginResponse';
/**
 *
 * @export
 * @interface OriginsResponse
 */
export interface OriginsResponse {
    /**
     *
     * @type {Array<OriginResponse>}
     * @memberof OriginsResponse
     */
    origins?: Array<OriginResponse>;
}
export declare function OriginsResponseFromJSON(json: any): OriginsResponse;
export declare function OriginsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OriginsResponse;
export declare function OriginsResponseToJSON(value?: OriginsResponse | null): any;
