/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface OriginResponse
 */
export interface OriginResponse {
    /**
     *
     * @type {string}
     * @memberof OriginResponse
     */
    id?: string;
    /**
     * An [RFC 6454](https://www.rfc-editor.org/rfc/rfc6454) valid url. Must not include any paths. A single wildcard (*) can be used as the first subdomain.
     * @type {string}
     * @memberof OriginResponse
     */
    origin?: string;
    /**
     *
     * @type {Date}
     * @memberof OriginResponse
     */
    createdAt?: Date;
    /**
     *
     * @type {string}
     * @memberof OriginResponse
     */
    projectEnvironmentId?: string;
}
export declare function OriginResponseFromJSON(json: any): OriginResponse;
export declare function OriginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OriginResponse;
export declare function OriginResponseToJSON(value?: OriginResponse | null): any;
