/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccessOutcomeEnum } from './AccessOutcomeEnum';
/**
 *
 * @export
 * @interface PostAllowlistsRequest
 */
export interface PostAllowlistsRequest {
    /**
     *
     * @type {string}
     * @memberof PostAllowlistsRequest
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof PostAllowlistsRequest
     */
    scope?: string;
    /**
     *
     * @type {AccessOutcomeEnum}
     * @memberof PostAllowlistsRequest
     */
    outcome?: AccessOutcomeEnum;
}
export declare function PostAllowlistsRequestFromJSON(json: any): PostAllowlistsRequest;
export declare function PostAllowlistsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAllowlistsRequest;
export declare function PostAllowlistsRequestToJSON(value?: PostAllowlistsRequest | null): any;
