/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PostAllowlistEntriesRequest
 */
export interface PostAllowlistEntriesRequest {
    /**
     * Valid blockchain wallet address, must be an alphanumeric string without any special characters
     * @type {string}
     * @memberof PostAllowlistEntriesRequest
     */
    walletPublicKey?: string;
    /**
     *
     * @type {string}
     * @memberof PostAllowlistEntriesRequest
     */
    email?: string;
    /**
     *
     * @type {string}
     * @memberof PostAllowlistEntriesRequest
     */
    alias?: string;
}
export declare function PostAllowlistEntriesRequestFromJSON(json: any): PostAllowlistEntriesRequest;
export declare function PostAllowlistEntriesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAllowlistEntriesRequest;
export declare function PostAllowlistEntriesRequestToJSON(value?: PostAllowlistEntriesRequest | null): any;
