/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectSettings } from './ProjectSettings';
/**
 *
 * @export
 * @interface ProjectEnvironment
 */
export interface ProjectEnvironment {
    /**
     *
     * @type {string}
     * @memberof ProjectEnvironment
     */
    id: string;
    /**
     *
     * @type {ProjectSettings}
     * @memberof ProjectEnvironment
     */
    settings?: ProjectSettings;
    /**
     *
     * @type {Date}
     * @memberof ProjectEnvironment
     */
    createdAt?: Date;
    /**
     *
     * @type {Date}
     * @memberof ProjectEnvironment
     */
    updatedAt?: Date;
    /**
     *
     * @type {string}
     * @memberof ProjectEnvironment
     */
    sdkVersion?: string;
}
export declare function ProjectEnvironmentFromJSON(json: any): ProjectEnvironment;
export declare function ProjectEnvironmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectEnvironment;
export declare function ProjectEnvironmentToJSON(value?: ProjectEnvironment | null): any;
