/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Duration } from './Duration';
import { SupportedSecurityMethods } from './SupportedSecurityMethods';
/**
 *
 * @export
 * @interface ProjectSettingsSdkEmbeddedWallets
 */
export interface ProjectSettingsSdkEmbeddedWallets {
    /**
     *
     * @type {boolean}
     * @memberof ProjectSettingsSdkEmbeddedWallets
     */
    automaticEmbeddedWalletCreation?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ProjectSettingsSdkEmbeddedWallets
     */
    emailRecoveryEnabled?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ProjectSettingsSdkEmbeddedWallets
     */
    forceAuthenticatorAtSignup?: boolean;
    /**
     *
     * @type {Duration}
     * @memberof ProjectSettingsSdkEmbeddedWallets
     */
    sessionKeyDuration?: Duration;
    /**
     *
     * @type {SupportedSecurityMethods}
     * @memberof ProjectSettingsSdkEmbeddedWallets
     */
    supportedSecurityMethods?: SupportedSecurityMethods;
}
export declare function ProjectSettingsSdkEmbeddedWalletsFromJSON(json: any): ProjectSettingsSdkEmbeddedWallets;
export declare function ProjectSettingsSdkEmbeddedWalletsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSettingsSdkEmbeddedWallets;
export declare function ProjectSettingsSdkEmbeddedWalletsToJSON(value?: ProjectSettingsSdkEmbeddedWallets | null): any;
