'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
function ProjectRequestFromJSON(json) {
    return ProjectRequestFromJSONTyped(json);
}
function ProjectRequestFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'name': json['name'],
    };
}
function ProjectRequestToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'name': value.name,
    };
}

exports.ProjectRequestFromJSON = ProjectRequestFromJSON;
exports.ProjectRequestFromJSONTyped = ProjectRequestFromJSONTyped;
exports.ProjectRequestToJSON = ProjectRequestToJSON;
