/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectProjectEnvironments } from './ProjectProjectEnvironments';
/**
 *
 * @export
 * @interface Project
 */
export interface Project {
    /**
     *
     * @type {string}
     * @memberof Project
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    organizationId: string;
    /**
     *
     * @type {Array<ProjectProjectEnvironments>}
     * @memberof Project
     */
    projectEnvironments?: Array<ProjectProjectEnvironments>;
}
export declare function ProjectFromJSON(json: any): Project;
export declare function ProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Project;
export declare function ProjectToJSON(value?: Project | null): any;
