/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmbeddedWalletSecurityMethod } from './EmbeddedWalletSecurityMethod';
import { ProjectSettingsSdkEmbeddedWallets } from './ProjectSettingsSdkEmbeddedWallets';
import { ProjectSettingsSdkSocialSignIn } from './ProjectSettingsSdkSocialSignIn';
import { ProjectSettingsSdkWalletConnect } from './ProjectSettingsSdkWalletConnect';
import { SdkView } from './SdkView';
/**
 *
 * @export
 * @interface ProjectSettingsSdk
 */
export interface ProjectSettingsSdk {
    /**
     *
     * @type {ProjectSettingsSdkSocialSignIn}
     * @memberof ProjectSettingsSdk
     */
    socialSignIn?: ProjectSettingsSdkSocialSignIn;
    /**
     *
     * @type {boolean}
     * @memberof ProjectSettingsSdk
     */
    multiWallet?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ProjectSettingsSdk
     */
    multiWalletUnlinkDisabled?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ProjectSettingsSdk
     */
    confirmWalletTransfers?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ProjectSettingsSdk
     */
    onrampFunding?: boolean;
    /**
     * passkeyEmbeddedWalletEnabled is deprecated as of v0.19. Please enable embedded wallets using the provider API.
     * @type {boolean}
     * @memberof ProjectSettingsSdk
     */
    passkeyEmbeddedWalletEnabled?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ProjectSettingsSdk
     */
    automaticEmbeddedWalletCreation?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ProjectSettingsSdk
     */
    passkeyEmbeddedWalletRecoveryEnabled?: boolean;
    /**
     * Embedded wallet authenticator security methods required upon creation of the embedded wallet at onboarding
     * @type {Array<EmbeddedWalletSecurityMethod>}
     * @memberof ProjectSettingsSdk
     */
    embeddedWalletSecurityMethods?: Array<EmbeddedWalletSecurityMethod>;
    /**
     *
     * @type {ProjectSettingsSdkEmbeddedWallets}
     * @memberof ProjectSettingsSdk
     */
    embeddedWallets?: ProjectSettingsSdkEmbeddedWallets;
    /**
     *
     * @type {ProjectSettingsSdkWalletConnect}
     * @memberof ProjectSettingsSdk
     */
    walletConnect?: ProjectSettingsSdkWalletConnect;
    /**
     *
     * @type {boolean}
     * @memberof ProjectSettingsSdk
     */
    confirmEmailProviderForVerify?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ProjectSettingsSdk
     */
    displayDynamicMessaging?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ProjectSettingsSdk
     */
    hideNetworkInDynamicWidget?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ProjectSettingsSdk
     */
    preventOrphanedAccounts?: boolean;
    /**
     * Configs used to create the views in the sdk.
     * @type {Array<SdkView>}
     * @memberof ProjectSettingsSdk
     */
    views?: Array<SdkView>;
}
export declare function ProjectSettingsSdkFromJSON(json: any): ProjectSettingsSdk;
export declare function ProjectSettingsSdkFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSettingsSdk;
export declare function ProjectSettingsSdkToJSON(value?: ProjectSettingsSdk | null): any;
