/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ProjectSettingsGeneral
 */
export interface ProjectSettingsGeneral {
    /**
     *
     * @type {string}
     * @memberof ProjectSettingsGeneral
     */
    displayName?: string;
    /**
     *
     * @type {string}
     * @memberof ProjectSettingsGeneral
     */
    supportEmail?: string;
    /**
     *
     * @type {string}
     * @memberof ProjectSettingsGeneral
     */
    supportText?: string;
    /**
     *
     * @type {string}
     * @memberof ProjectSettingsGeneral
     */
    appLogo?: string;
    /**
     *
     * @type {string}
     * @memberof ProjectSettingsGeneral
     */
    imageUserNotInAccessList?: string;
    /**
     *
     * @type {string}
     * @memberof ProjectSettingsGeneral
     */
    imageUserInAccessList?: string;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof ProjectSettingsGeneral
     */
    supportUrls?: {
        [key: string]: string;
    };
    /**
     *
     * @type {string}
     * @memberof ProjectSettingsGeneral
     */
    collectUserDataWelcomeHeader?: string;
    /**
     *
     * @type {string}
     * @memberof ProjectSettingsGeneral
     */
    collectUserDataWelcomeMessage?: string;
    /**
     *
     * @type {boolean}
     * @memberof ProjectSettingsGeneral
     */
    skipOptionalKYCFieldDuringOnboarding?: boolean;
    /**
     *
     * @type {string}
     * @memberof ProjectSettingsGeneral
     */
    emailCompanyName?: string;
}
export declare function ProjectSettingsGeneralFromJSON(json: any): ProjectSettingsGeneral;
export declare function ProjectSettingsGeneralFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSettingsGeneral;
export declare function ProjectSettingsGeneralToJSON(value?: ProjectSettingsGeneral | null): any;
