/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ProjectProjectEnvironments
 */
export interface ProjectProjectEnvironments {
    /**
     *
     * @type {string}
     * @memberof ProjectProjectEnvironments
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof ProjectProjectEnvironments
     */
    environmentName?: string;
}
export declare function ProjectProjectEnvironmentsFromJSON(json: any): ProjectProjectEnvironments;
export declare function ProjectProjectEnvironmentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectProjectEnvironments;
export declare function ProjectProjectEnvironmentsToJSON(value?: ProjectProjectEnvironments | null): any;
