/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ProjectRequest
 */
export interface ProjectRequest {
    /**
     *
     * @type {string}
     * @memberof ProjectRequest
     */
    name: string;
}
export declare function ProjectRequestFromJSON(json: any): ProjectRequest;
export declare function ProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectRequest;
export declare function ProjectRequestToJSON(value?: ProjectRequest | null): any;
