/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProviderUrl } from './ProviderUrl';
/**
 *
 * @export
 * @interface ProviderUrlsResponse
 */
export interface ProviderUrlsResponse {
    /**
     *
     * @type {Array<ProviderUrl>}
     * @memberof ProviderUrlsResponse
     */
    providerUrls?: Array<ProviderUrl>;
}
export declare function ProviderUrlsResponseFromJSON(json: any): ProviderUrlsResponse;
export declare function ProviderUrlsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderUrlsResponse;
export declare function ProviderUrlsResponseToJSON(value?: ProviderUrlsResponse | null): any;
