/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Provider } from './Provider';
/**
 *
 * @export
 * @interface ProvidersResponse
 */
export interface ProvidersResponse {
    /**
     *
     * @type {Array<Provider>}
     * @memberof ProvidersResponse
     */
    providers?: Array<Provider>;
}
export declare function ProvidersResponseFromJSON(json: any): ProvidersResponse;
export declare function ProvidersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProvidersResponse;
export declare function ProvidersResponseToJSON(value?: ProvidersResponse | null): any;
