/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProviderEnum } from './ProviderEnum';
/**
 * Request body to create a new provider. The provider will be not enabled by default.
 * @export
 * @interface ProviderCreateRequest
 */
export interface ProviderCreateRequest {
    /**
     *
     * @type {ProviderEnum}
     * @memberof ProviderCreateRequest
     */
    provider: ProviderEnum;
    /**
     * Standard OAuth client ID. For more information, see: https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/. For Apple, this is also known as the Service ID.
     * @type {string}
     * @memberof ProviderCreateRequest
     */
    clientId?: string;
    /**
     * Standard OAuth client secret key. For more information, see: https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/
     * @type {string}
     * @memberof ProviderCreateRequest
     */
    clientSecret?: string;
    /**
     * Some providers require additional information, typically called a project ID or site ID
     * @type {string}
     * @memberof ProviderCreateRequest
     */
    providerProjectId?: string;
    /**
     * The default chain id the SDK should use
     * @type {number}
     * @memberof ProviderCreateRequest
     */
    defaultChainId?: number;
    /**
     * CAIP-2 Chain ID (https://github.com/ChainAgnostic/CAIPs/blob/main/CAIPs/caip-2.md)
     * @type {string}
     * @memberof ProviderCreateRequest
     */
    defaultChain?: string;
    /**
     * The url of the site to go to export wallets private keys
     * @type {string}
     * @memberof ProviderCreateRequest
     */
    keyExportUrl?: string;
    /**
     * The url of the terms and conditions or privacy policy needed to be shown to the client when creating a new provider that requires terms and conditions to be signed before starting configuration.
     * @type {string}
     * @memberof ProviderCreateRequest
     */
    termsUrl?: string;
    /**
     *
     * @type {boolean}
     * @memberof ProviderCreateRequest
     */
    useDynamicCredentials?: boolean;
    /**
     * Key ID required for Apple Oauth2 applications. This is the identifier for a private key.
     * @type {string}
     * @memberof ProviderCreateRequest
     */
    appleKeyId?: string;
    /**
     * Team ID required for Apple Oauth2 applications. This is associated with the Apple developer membership account.
     * @type {string}
     * @memberof ProviderCreateRequest
     */
    appleTeamId?: string;
}
export declare function ProviderCreateRequestFromJSON(json: any): ProviderCreateRequest;
export declare function ProviderCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderCreateRequest;
export declare function ProviderCreateRequestToJSON(value?: ProviderCreateRequest | null): any;
