'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
exports.RoleEnum = void 0;
(function (RoleEnum) {
    RoleEnum["Admin"] = "admin";
    RoleEnum["Viewer"] = "viewer";
})(exports.RoleEnum || (exports.RoleEnum = {}));
function RoleEnumFromJSON(json) {
    return RoleEnumFromJSONTyped(json);
}
function RoleEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function RoleEnumToJSON(value) {
    return value;
}

exports.RoleEnumFromJSON = RoleEnumFromJSON;
exports.RoleEnumFromJSONTyped = RoleEnumFromJSONTyped;
exports.RoleEnumToJSON = RoleEnumToJSON;
