/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Session
 */
export interface Session {
    /**
     *
     * @type {string}
     * @memberof Session
     */
    id?: string;
    /**
     *
     * @type {Date}
     * @memberof Session
     */
    createdAt?: Date;
    /**
     *
     * @type {string}
     * @memberof Session
     */
    ipAddress?: string;
    /**
     *
     * @type {Date}
     * @memberof Session
     */
    revokedAt?: Date | null;
}
export declare function SessionFromJSON(json: any): Session;
export declare function SessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Session;
export declare function SessionToJSON(value?: Session | null): any;
