/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum ShortChainNameEnum {
    Evm = "evm"
}
export declare function ShortChainNameEnumFromJSON(json: any): ShortChainNameEnum;
export declare function ShortChainNameEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShortChainNameEnum;
export declare function ShortChainNameEnumToJSON(value?: ShortChainNameEnum | null): any;
