/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface TokenCreatedBy
 */
export interface TokenCreatedBy {
    /**
     *
     * @type {string}
     * @memberof TokenCreatedBy
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof TokenCreatedBy
     */
    alias?: string;
    /**
     *
     * @type {string}
     * @memberof TokenCreatedBy
     */
    firstName?: string;
    /**
     *
     * @type {string}
     * @memberof TokenCreatedBy
     */
    lastName?: string;
    /**
     *
     * @type {string}
     * @memberof TokenCreatedBy
     */
    email?: string;
}
export declare function TokenCreatedByFromJSON(json: any): TokenCreatedBy;
export declare function TokenCreatedByFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenCreatedBy;
export declare function TokenCreatedByToJSON(value?: TokenCreatedBy | null): any;
