/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
function TokenAddressFromJSON(json) {
    return TokenAddressFromJSONTyped(json);
}
function TokenAddressFromJSONTyped(json, ignoreDiscriminator) {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        'networkId': json['networkId'],
        'contractAddress': json['contractAddress'],
    };
}
function TokenAddressToJSON(value) {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        'networkId': value.networkId,
        'contractAddress': value.contractAddress,
    };
}

export { TokenAddressFromJSON, TokenAddressFromJSONTyped, TokenAddressToJSON };
