/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TokenCreatedBy } from './TokenCreatedBy';
import { TokenWithRawProjectEnvironment } from './TokenWithRawProjectEnvironment';
/**
 *
 * @export
 * @interface Token
 */
export interface Token {
    /**
     *
     * @type {string}
     * @memberof Token
     */
    id: string;
    /**
     * A 6-character alpha-numeric string checksum of the random API Token. The last 6 characters of the raw token
     * @type {string}
     * @memberof Token
     */
    checksum: string;
    /**
     *
     * @type {TokenCreatedBy}
     * @memberof Token
     */
    createdBy: TokenCreatedBy;
    /**
     *
     * @type {Date}
     * @memberof Token
     */
    createdAt: Date;
    /**
     *
     * @type {string}
     * @memberof Token
     */
    note?: string;
    /**
     *
     * @type {string}
     * @memberof Token
     */
    projectEnvironmentId: string;
    /**
     *
     * @type {TokenWithRawProjectEnvironment}
     * @memberof Token
     */
    projectEnvironment: TokenWithRawProjectEnvironment;
}
export declare function TokenFromJSON(json: any): Token;
export declare function TokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Token;
export declare function TokenToJSON(value?: Token | null): any;
