/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Defines one token address connected with network Id on which it's working
 * @export
 * @interface TokenAddress
 */
export interface TokenAddress {
    /**
     * Id of the network
     * @type {number}
     * @memberof TokenAddress
     */
    networkId: number;
    /**
     * Valid blockchain wallet address, must be an alphanumeric string without any special characters
     * @type {string}
     * @memberof TokenAddress
     */
    contractAddress: string;
}
export declare function TokenAddressFromJSON(json: any): TokenAddress;
export declare function TokenAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenAddress;
export declare function TokenAddressToJSON(value?: TokenAddress | null): any;
