/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TokenCreatedBy } from './TokenCreatedBy';
import { TokenWithRawProjectEnvironment } from './TokenWithRawProjectEnvironment';
/**
 *
 * @export
 * @interface TokenWithRaw
 */
export interface TokenWithRaw {
    /**
     *
     * @type {string}
     * @memberof TokenWithRaw
     */
    id: string;
    /**
     * The actual token created. If you do not save it, it can never be retrieved again
     * @type {string}
     * @memberof TokenWithRaw
     */
    rawToken: string;
    /**
     * A 6-character alpha-numeric string checksum of the random API Token. The last 6 characters of the raw token
     * @type {string}
     * @memberof TokenWithRaw
     */
    checksum: string;
    /**
     *
     * @type {TokenCreatedBy}
     * @memberof TokenWithRaw
     */
    createdBy: TokenCreatedBy;
    /**
     * Only active tokens can be used.
     * @type {boolean}
     * @memberof TokenWithRaw
     */
    active?: boolean;
    /**
     *
     * @type {Date}
     * @memberof TokenWithRaw
     */
    createdAt: Date;
    /**
     *
     * @type {string}
     * @memberof TokenWithRaw
     */
    note?: string;
    /**
     *
     * @type {string}
     * @memberof TokenWithRaw
     */
    projectEnvironmentId: string;
    /**
     *
     * @type {TokenWithRawProjectEnvironment}
     * @memberof TokenWithRaw
     */
    projectEnvironment: TokenWithRawProjectEnvironment;
}
export declare function TokenWithRawFromJSON(json: any): TokenWithRaw;
export declare function TokenWithRawFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenWithRaw;
export declare function TokenWithRawToJSON(value?: TokenWithRaw | null): any;
