/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Token } from './Token';
/**
 *
 * @export
 * @interface TokensResponse
 */
export interface TokensResponse {
    /**
     *
     * @type {Array<Token>}
     * @memberof TokensResponse
     */
    tokens?: Array<Token>;
}
export declare function TokensResponseFromJSON(json: any): TokensResponse;
export declare function TokensResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokensResponse;
export declare function TokensResponseToJSON(value?: TokensResponse | null): any;
