/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProviderEnum } from './ProviderEnum';
/**
 * Contains information which the integrating client of this API can use to tailor an experience to a customer to fix the underlying issue that triggered this error.
 * @export
 * @interface UnprocessableEntityErrorPayload
 */
export interface UnprocessableEntityErrorPayload {
    /**
     *
     * @type {string}
     * @memberof UnprocessableEntityErrorPayload
     */
    email?: string;
    /**
     *
     * @type {ProviderEnum}
     * @memberof UnprocessableEntityErrorPayload
     */
    loginProvider?: ProviderEnum;
    /**
     *
     * @type {string}
     * @memberof UnprocessableEntityErrorPayload
     */
    embeddedWalletName?: string;
    /**
     *
     * @type {ProviderEnum}
     * @memberof UnprocessableEntityErrorPayload
     */
    embeddedSocialSigninProvider?: ProviderEnum;
}
export declare function UnprocessableEntityErrorPayloadFromJSON(json: any): UnprocessableEntityErrorPayload;
export declare function UnprocessableEntityErrorPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnprocessableEntityErrorPayload;
export declare function UnprocessableEntityErrorPayloadToJSON(value?: UnprocessableEntityErrorPayload | null): any;
