/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UpdateProjectResponse
 */
export interface UpdateProjectResponse {
    /**
     *
     * @type {string}
     * @memberof UpdateProjectResponse
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateProjectResponse
     */
    name?: string;
}
export declare function UpdateProjectResponseFromJSON(json: any): UpdateProjectResponse;
export declare function UpdateProjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProjectResponse;
export declare function UpdateProjectResponseToJSON(value?: UpdateProjectResponse | null): any;
