/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmailVerificationCreateResponse } from './EmailVerificationCreateResponse';
import { NextViewEnum } from './NextViewEnum';
import { SdkUser } from './SdkUser';
/**
 *
 * @export
 * @interface UpdateSelfResponse
 */
export interface UpdateSelfResponse {
    /**
     *
     * @type {SdkUser}
     * @memberof UpdateSelfResponse
     */
    user: SdkUser;
    /**
     *
     * @type {NextViewEnum}
     * @memberof UpdateSelfResponse
     */
    nextView: NextViewEnum;
    /**
     *
     * @type {EmailVerificationCreateResponse}
     * @memberof UpdateSelfResponse
     */
    emailVerification?: EmailVerificationCreateResponse;
    /**
     * Encoded JWT token
     * @type {string}
     * @memberof UpdateSelfResponse
     */
    jwt: string;
    /**
     * Encoded JWT token
     * @type {string}
     * @memberof UpdateSelfResponse
     */
    minifiedJwt: string;
}
export declare function UpdateSelfResponseFromJSON(json: any): UpdateSelfResponse;
export declare function UpdateSelfResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSelfResponse;
export declare function UpdateSelfResponseToJSON(value?: UpdateSelfResponse | null): any;
