/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Wallet } from './Wallet';
/**
 *
 * @export
 * @interface UserWalletsResponse
 */
export interface UserWalletsResponse {
    /**
     *
     * @type {number}
     * @memberof UserWalletsResponse
     */
    count: number;
    /**
     *
     * @type {Array<Wallet>}
     * @memberof UserWalletsResponse
     */
    wallets: Array<Wallet>;
}
export declare function UserWalletsResponseFromJSON(json: any): UserWalletsResponse;
export declare function UserWalletsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWalletsResponse;
export declare function UserWalletsResponseToJSON(value?: UserWalletsResponse | null): any;
