/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChainEnum } from './ChainEnum';
import { UserFilterableFieldsEnum } from './UserFilterableFieldsEnum';
/**
 *
 * @export
 * @interface UserSearchFilterParams
 */
export interface UserSearchFilterParams {
    /**
     *
     * @type {string}
     * @memberof UserSearchFilterParams
     */
    filterValue?: string;
    /**
     *
     * @type {UserFilterableFieldsEnum}
     * @memberof UserSearchFilterParams
     */
    filterColumn?: UserFilterableFieldsEnum;
    /**
     *
     * @type {ChainEnum}
     * @memberof UserSearchFilterParams
     */
    chain?: ChainEnum;
}
export declare function UserSearchFilterParamsFromJSON(json: any): UserSearchFilterParams;
export declare function UserSearchFilterParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSearchFilterParams;
export declare function UserSearchFilterParamsToJSON(value?: UserSearchFilterParams | null): any;
