/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './User';
/**
 *
 * @export
 * @interface UsersResponse
 */
export interface UsersResponse {
    /**
     *
     * @type {number}
     * @memberof UsersResponse
     */
    count?: number;
    /**
     *
     * @type {Array<User>}
     * @memberof UsersResponse
     */
    users?: Array<User>;
}
export declare function UsersResponseFromJSON(json: any): UsersResponse;
export declare function UsersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersResponse;
export declare function UsersResponseToJSON(value?: UsersResponse | null): any;
