'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
exports.UserFilterableFieldsEnum = void 0;
(function (UserFilterableFieldsEnum) {
    UserFilterableFieldsEnum["All"] = "all";
    UserFilterableFieldsEnum["Id"] = "id";
    UserFilterableFieldsEnum["WalletPublicKey"] = "walletPublicKey";
    UserFilterableFieldsEnum["Email"] = "email";
    UserFilterableFieldsEnum["Alias"] = "alias";
    UserFilterableFieldsEnum["FirstName"] = "firstName";
    UserFilterableFieldsEnum["LastName"] = "lastName";
    UserFilterableFieldsEnum["PhoneNumber"] = "phoneNumber";
    UserFilterableFieldsEnum["JobTitle"] = "jobTitle";
    UserFilterableFieldsEnum["Wallet"] = "wallet";
    UserFilterableFieldsEnum["Username"] = "username";
})(exports.UserFilterableFieldsEnum || (exports.UserFilterableFieldsEnum = {}));
function UserFilterableFieldsEnumFromJSON(json) {
    return UserFilterableFieldsEnumFromJSONTyped(json);
}
function UserFilterableFieldsEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function UserFilterableFieldsEnumToJSON(value) {
    return value;
}

exports.UserFilterableFieldsEnumFromJSON = UserFilterableFieldsEnumFromJSON;
exports.UserFilterableFieldsEnumFromJSONTyped = UserFilterableFieldsEnumFromJSONTyped;
exports.UserFilterableFieldsEnumToJSON = UserFilterableFieldsEnumToJSON;
