/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum UserFilterableFieldsEnum {
    All = "all",
    Id = "id",
    WalletPublicKey = "walletPublicKey",
    Email = "email",
    Alias = "alias",
    FirstName = "firstName",
    LastName = "lastName",
    PhoneNumber = "phoneNumber",
    JobTitle = "jobTitle",
    Wallet = "wallet",
    Username = "username"
}
export declare function UserFilterableFieldsEnumFromJSON(json: any): UserFilterableFieldsEnum;
export declare function UserFilterableFieldsEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFilterableFieldsEnum;
export declare function UserFilterableFieldsEnumToJSON(value?: UserFilterableFieldsEnum | null): any;
