/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SdkUser } from './SdkUser';
/**
 *
 * @export
 * @interface VerifyResponse
 */
export interface VerifyResponse {
    /**
     * Encoded JWT token
     * @type {string}
     * @memberof VerifyResponse
     */
    jwt: string;
    /**
     *
     * @type {SdkUser}
     * @memberof VerifyResponse
     */
    user: SdkUser;
    /**
     * Encoded JWT token
     * @type {string}
     * @memberof VerifyResponse
     */
    minifiedJwt: string;
}
export declare function VerifyResponseFromJSON(json: any): VerifyResponse;
export declare function VerifyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyResponse;
export declare function VerifyResponseToJSON(value?: VerifyResponse | null): any;
