/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum VisitorFilterableFieldsEnum {
    All = "all",
    Id = "id",
    WalletPublicKey = "walletPublicKey"
}
export declare function VisitorFilterableFieldsEnumFromJSON(json: any): VisitorFilterableFieldsEnum;
export declare function VisitorFilterableFieldsEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): VisitorFilterableFieldsEnum;
export declare function VisitorFilterableFieldsEnumToJSON(value?: VisitorFilterableFieldsEnum | null): any;
