'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
exports.VisitorFilterableFieldsEnum = void 0;
(function (VisitorFilterableFieldsEnum) {
    VisitorFilterableFieldsEnum["All"] = "all";
    VisitorFilterableFieldsEnum["Id"] = "id";
    VisitorFilterableFieldsEnum["WalletPublicKey"] = "walletPublicKey";
})(exports.VisitorFilterableFieldsEnum || (exports.VisitorFilterableFieldsEnum = {}));
function VisitorFilterableFieldsEnumFromJSON(json) {
    return VisitorFilterableFieldsEnumFromJSONTyped(json);
}
function VisitorFilterableFieldsEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function VisitorFilterableFieldsEnumToJSON(value) {
    return value;
}

exports.VisitorFilterableFieldsEnumFromJSON = VisitorFilterableFieldsEnumFromJSON;
exports.VisitorFilterableFieldsEnumFromJSONTyped = VisitorFilterableFieldsEnumFromJSONTyped;
exports.VisitorFilterableFieldsEnumToJSON = VisitorFilterableFieldsEnumToJSON;
