/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChainEnum } from './ChainEnum';
import { WalletProviderEnum } from './WalletProviderEnum';
/**
 *
 * @export
 * @interface Visitor
 */
export interface Visitor {
    /**
     *
     * @type {string}
     * @memberof Visitor
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof Visitor
     */
    address: string;
    /**
     *
     * @type {ChainEnum}
     * @memberof Visitor
     */
    chain: ChainEnum;
    /**
     *
     * @type {string}
     * @memberof Visitor
     */
    walletName: string;
    /**
     *
     * @type {WalletProviderEnum}
     * @memberof Visitor
     */
    provider: WalletProviderEnum;
    /**
     *
     * @type {Date}
     * @memberof Visitor
     */
    createdAt: Date;
    /**
     *
     * @type {string}
     * @memberof Visitor
     */
    projectEnvironmentId?: string;
}
export declare function VisitorFromJSON(json: any): Visitor;
export declare function VisitorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Visitor;
export declare function VisitorToJSON(value?: Visitor | null): any;
