/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChainEnum } from './ChainEnum';
import { VisitorFilterableFieldsEnum } from './VisitorFilterableFieldsEnum';
/**
 *
 * @export
 * @interface VisitorSearchFilterParams
 */
export interface VisitorSearchFilterParams {
    /**
     *
     * @type {string}
     * @memberof VisitorSearchFilterParams
     */
    filterValue?: string;
    /**
     *
     * @type {VisitorFilterableFieldsEnum}
     * @memberof VisitorSearchFilterParams
     */
    filterColumn?: VisitorFilterableFieldsEnum;
    /**
     *
     * @type {ChainEnum}
     * @memberof VisitorSearchFilterParams
     */
    chain?: ChainEnum;
}
export declare function VisitorSearchFilterParamsFromJSON(json: any): VisitorSearchFilterParams;
export declare function VisitorSearchFilterParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VisitorSearchFilterParams;
export declare function VisitorSearchFilterParamsToJSON(value?: VisitorSearchFilterParams | null): any;
