/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChainEnum } from './ChainEnum';
import { WalletProperties } from './WalletProperties';
import { WalletProviderEnum } from './WalletProviderEnum';
/**
 *
 * @export
 * @interface Wallet
 */
export interface Wallet {
    /**
     *
     * @type {string}
     * @memberof Wallet
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof Wallet
     */
    name: string;
    /**
     *
     * @type {ChainEnum}
     * @memberof Wallet
     */
    chain: ChainEnum;
    /**
     * Valid blockchain wallet address, must be an alphanumeric string without any special characters
     * @type {string}
     * @memberof Wallet
     */
    publicKey: string;
    /**
     *
     * @type {WalletProviderEnum}
     * @memberof Wallet
     */
    provider: WalletProviderEnum;
    /**
     *
     * @type {WalletProperties}
     * @memberof Wallet
     */
    properties?: WalletProperties;
}
export declare function WalletFromJSON(json: any): Wallet;
export declare function WalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): Wallet;
export declare function WalletToJSON(value?: Wallet | null): any;
