/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Webhook } from './Webhook';
/**
 *
 * @export
 * @interface WebhooksResponse
 */
export interface WebhooksResponse {
    /**
     *
     * @type {string}
     * @memberof WebhooksResponse
     */
    cursor?: string;
    /**
     *
     * @type {Array<Webhook>}
     * @memberof WebhooksResponse
     */
    data?: Array<Webhook>;
}
export declare function WebhooksResponseFromJSON(json: any): WebhooksResponse;
export declare function WebhooksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhooksResponse;
export declare function WebhooksResponseToJSON(value?: WebhooksResponse | null): any;
