/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface WebhookMessageRedeliveryResponse
 */
export interface WebhookMessageRedeliveryResponse {
    /**
     *
     * @type {string}
     * @memberof WebhookMessageRedeliveryResponse
     */
    message?: string;
}
export declare function WebhookMessageRedeliveryResponseFromJSON(json: any): WebhookMessageRedeliveryResponse;
export declare function WebhookMessageRedeliveryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookMessageRedeliveryResponse;
export declare function WebhookMessageRedeliveryResponseToJSON(value?: WebhookMessageRedeliveryResponse | null): any;
