/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface WebhookUpdateRequest
 */
export interface WebhookUpdateRequest {
    /**
     *
     * @type {string}
     * @memberof WebhookUpdateRequest
     */
    url: string;
    /**
     *
     * @type {boolean}
     * @memberof WebhookUpdateRequest
     */
    isEnabled: boolean;
    /**
     *
     * @type {Array<string>}
     * @memberof WebhookUpdateRequest
     */
    events: Array<string>;
}
export declare function WebhookUpdateRequestFromJSON(json: any): WebhookUpdateRequest;
export declare function WebhookUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookUpdateRequest;
export declare function WebhookUpdateRequestToJSON(value?: WebhookUpdateRequest | null): any;
