/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface WebhookCreateRequest
 */
export interface WebhookCreateRequest {
    /**
     *
     * @type {string}
     * @memberof WebhookCreateRequest
     */
    url: string;
    /**
     *
     * @type {boolean}
     * @memberof WebhookCreateRequest
     */
    isEnabled: boolean;
    /**
     *
     * @type {Array<string>}
     * @memberof WebhookCreateRequest
     */
    events: Array<string>;
}
export declare function WebhookCreateRequestFromJSON(json: any): WebhookCreateRequest;
export declare function WebhookCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookCreateRequest;
export declare function WebhookCreateRequestToJSON(value?: WebhookCreateRequest | null): any;
