/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface WebhookMessage
 */
export interface WebhookMessage {
    /**
     *
     * @type {string}
     * @memberof WebhookMessage
     */
    deliveryId: string;
    /**
     *
     * @type {string}
     * @memberof WebhookMessage
     */
    eventId: string;
    /**
     *
     * @type {string}
     * @memberof WebhookMessage
     */
    messageId: string;
    /**
     *
     * @type {string}
     * @memberof WebhookMessage
     */
    environmentId: string;
    /**
     *
     * @type {string}
     * @memberof WebhookMessage
     */
    webhookId: string;
    /**
     *
     * @type {string}
     * @memberof WebhookMessage
     */
    status: string;
    /**
     *
     * @type {Date}
     * @memberof WebhookMessage
     */
    deliveredAt: Date;
    /**
     *
     * @type {Date}
     * @memberof WebhookMessage
     */
    messageCreatedAt: Date;
    /**
     *
     * @type {Date}
     * @memberof WebhookMessage
     */
    eventReceivedAt: Date;
    /**
     *
     * @type {Date}
     * @memberof WebhookMessage
     */
    eventCreatedAt: Date;
    /**
     *
     * @type {number}
     * @memberof WebhookMessage
     */
    deliveryAttempt: number;
    /**
     *
     * @type {object}
     * @memberof WebhookMessage
     */
    request: object;
    /**
     *
     * @type {object}
     * @memberof WebhookMessage
     */
    response: object;
    /**
     *
     * @type {Date}
     * @memberof WebhookMessage
     */
    updatedAt: Date;
    /**
     *
     * @type {Date}
     * @memberof WebhookMessage
     */
    createdAt: Date;
}
export declare function WebhookMessageFromJSON(json: any): WebhookMessage;
export declare function WebhookMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookMessage;
export declare function WebhookMessageToJSON(value?: WebhookMessage | null): any;
