/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum WhenToImplementEnum {
    Yesterday = "yesterday",
    NextTwoWeeks = "nextTwoWeeks",
    NextTwoMonths = "nextTwoMonths",
    JustBrowsing = "justBrowsing"
}
export declare function WhenToImplementEnumFromJSON(json: any): WhenToImplementEnum;
export declare function WhenToImplementEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): WhenToImplementEnum;
export declare function WhenToImplementEnumToJSON(value?: WhenToImplementEnum | null): any;
