'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
exports.WhenToImplementEnum = void 0;
(function (WhenToImplementEnum) {
    WhenToImplementEnum["Yesterday"] = "yesterday";
    WhenToImplementEnum["NextTwoWeeks"] = "nextTwoWeeks";
    WhenToImplementEnum["NextTwoMonths"] = "nextTwoMonths";
    WhenToImplementEnum["JustBrowsing"] = "justBrowsing";
})(exports.WhenToImplementEnum || (exports.WhenToImplementEnum = {}));
function WhenToImplementEnumFromJSON(json) {
    return WhenToImplementEnumFromJSONTyped(json);
}
function WhenToImplementEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function WhenToImplementEnumToJSON(value) {
    return value;
}

exports.WhenToImplementEnumFromJSON = WhenToImplementEnumFromJSON;
exports.WhenToImplementEnumFromJSONTyped = WhenToImplementEnumFromJSONTyped;
exports.WhenToImplementEnumToJSON = WhenToImplementEnumToJSON;
