/* tslint:disable */
/* eslint-disable */
/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
var WhenToImplementEnum;
(function (WhenToImplementEnum) {
    WhenToImplementEnum["Yesterday"] = "yesterday";
    WhenToImplementEnum["NextTwoWeeks"] = "nextTwoWeeks";
    WhenToImplementEnum["NextTwoMonths"] = "nextTwoMonths";
    WhenToImplementEnum["JustBrowsing"] = "justBrowsing";
})(WhenToImplementEnum || (WhenToImplementEnum = {}));
function WhenToImplementEnumFromJSON(json) {
    return WhenToImplementEnumFromJSONTyped(json);
}
function WhenToImplementEnumFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function WhenToImplementEnumToJSON(value) {
    return value;
}

export { WhenToImplementEnum, WhenToImplementEnumFromJSON, WhenToImplementEnumFromJSONTyped, WhenToImplementEnumToJSON };
