'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var jsxRuntime = require('react/jsx-runtime');
var ZoomTransition = require('../../../../../../components/Transition/ZoomTransition/ZoomTransition.cjs');
require('../../../../../../components/Transition/SlideInUpTransition/SlideInUpTransition.cjs');
require('../../../../../../components/Transition/OpacityTransition/OpacityTransition.cjs');
require('react');
require('@dynamic-labs/utils');
require('../../../../../../context/DynamicContext/DynamicContext.cjs');
require('@dynamic-labs/wallet-connector-core');
require('../../../../../../context/CaptchaContext/CaptchaContext.cjs');
require('../../../../../../context/ErrorContext/ErrorContext.cjs');
require('../../../../../../context/ViewContext/ViewContext.cjs');
require('@dynamic-labs/sdk-api');
require('../../../../../../shared/logger.cjs');
require('@dynamic-labs/iconic');
require('@dynamic-labs/wallet-book');
require('../../../../../../utils/constants/colors.cjs');
require('../../../../../../shared/utils/classes/storage/localStorage.cjs');
require('viem');
require('../../../../../../shared/consts/index.cjs');
require('@dynamic-labs/multi-wallet');
require('../../../../../../context/AccessDeniedContext/AccessDeniedContext.cjs');
require('../../../../../../context/AccountExistsContext/AccountExistsContext.cjs');
require('../../../../../../config/ApiEndpoint.cjs');
require('../../../../../../context/EmailVerificationContext/EmailVerificationContext.cjs');
require('react-dom');
require('../../../../../../context/ThemeContext/ThemeContext.cjs');
require('@dynamic-labs/types');
require('yup');
require('react-i18next');
require('../../../../../../context/MockContext/MockContext.cjs');
require('../../../../../../utils/hooks/useUserUpdateRequest/useUpdateUser/useUpdateUser.cjs');
require('../../../../../../context/UserFieldEditorContext/UserFieldEditorContext.cjs');
require('@dynamic-labs/rpc-providers');
require('../../../../../../context/UserWalletsContext/UserWalletsContext.cjs');
var classNames = require('../../../../../../utils/functions/classNames/classNames.cjs');
require('../../../../../../components/Alert/Alert.cjs');
require('../../../../../../components/ShadowDOM/ShadowDOM.cjs');
require('../../../../../../components/IconButton/IconButton.cjs');
require('../../../../../../components/InlineWidget/InlineWidget.cjs');
require('../../../../../../components/MenuList/Dropdown/Dropdown.cjs');
require('../../../../../../components/Popper/Popper/Popper.cjs');
var PopperContext = require('../../../../../../components/Popper/PopperContext/PopperContext.cjs');
require('react-focus-lock');
require('formik');
require('i18next');
require('../../../../../../components/OverlayCard/OverlayCard.context.cjs');
require('../../../../../../context/FooterAnimationContext/index.cjs');
require('../../../../../../context/QrCodeContext/QrCodeContext.cjs');
require('../../../../../../context/WalletGroupContext/WalletGroupContext.cjs');
require('../../../DynamicWidgetHeader/DynamicWidgetHeader.cjs');
require('qrcode');
require('../../../../../../context/LoadingContext/LoadingContext.cjs');
require('../../../../context/DynamicWidgetContext.cjs');
require('../../../../../../components/UserProfile/parts/UserProfileField/components/VerifiedEmailIcon/VerifiedEmailIcon.cjs');
require('@dynamic-labs/viem-utils');
require('../../../../views/ManagePasskeysWidgetView/PasskeyCard/PasskeyCard.cjs');

const DynamicWidgetDropdown = ({ zIndex, isShown, onClose, children, className, contentClassName, }) => (jsxRuntime.jsx(ZoomTransition.ZoomTransition, { outDuration: 200, className: classNames.classNames('dynamic-widget-dropdown', className), isShown: isShown, children: jsxRuntime.jsx("div", { "data-testid": 'DynamicWidgetDropdown', style: { zIndex }, className: classNames.classNames('dynamic-widget-dropdown__root', contentClassName), children: jsxRuntime.jsx(PopperContext.PopperProvider, { children: children }) }) }));

exports.DynamicWidgetDropdown = DynamicWidgetDropdown;
