'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var jsxRuntime = require('react/jsx-runtime');
var classNames = require('../../../../../../utils/functions/classNames/classNames.cjs');
require('react');
require('@dynamic-labs/utils');
require('../../../../../../context/DynamicContext/DynamicContext.cjs');
require('@dynamic-labs/wallet-connector-core');
require('../../../../../../context/CaptchaContext/CaptchaContext.cjs');
require('../../../../../../context/ErrorContext/ErrorContext.cjs');
require('../../../../../../context/ViewContext/ViewContext.cjs');
require('@dynamic-labs/sdk-api');
require('../../../../../../shared/logger.cjs');
require('@dynamic-labs/iconic');
require('@dynamic-labs/wallet-book');
require('../../../../../../utils/constants/colors.cjs');
require('../../../../../../shared/utils/classes/storage/localStorage.cjs');
require('viem');
var usePreventPageScroll = require('../../../../../../shared/utils/hooks/usePreventPageScroll/usePreventPageScroll.cjs');
require('../../../../../../shared/consts/index.cjs');
require('@dynamic-labs/multi-wallet');
require('../../../../../../context/AccessDeniedContext/AccessDeniedContext.cjs');
require('../../../../../../context/AccountExistsContext/AccountExistsContext.cjs');
require('../../../../../../config/ApiEndpoint.cjs');
require('../../../../../../context/EmailVerificationContext/EmailVerificationContext.cjs');
require('react-dom');
require('../../../../../../context/ThemeContext/ThemeContext.cjs');
require('@dynamic-labs/types');
require('yup');
require('react-i18next');
require('../../../../../../context/MockContext/MockContext.cjs');
require('../../../../../../utils/hooks/useUserUpdateRequest/useUpdateUser/useUpdateUser.cjs');
require('../../../../../../context/UserFieldEditorContext/UserFieldEditorContext.cjs');
require('@dynamic-labs/rpc-providers');
require('../../../../../../context/UserWalletsContext/UserWalletsContext.cjs');
require('../../../../../../components/Transition/ZoomTransition/ZoomTransition.cjs');
require('../../../../../../components/Transition/SlideInUpTransition/SlideInUpTransition.cjs');
require('../../../../../../components/Transition/OpacityTransition/OpacityTransition.cjs');
require('../../../../../../components/ShadowDOM/ShadowDOM.cjs');
require('../../../../../../components/OverlayCard/OverlayCard.context.cjs');
require('../../../../../../context/FooterAnimationContext/index.cjs');
require('../../../../../../context/QrCodeContext/QrCodeContext.cjs');
require('../../../../../../context/WalletGroupContext/WalletGroupContext.cjs');
require('../../../DynamicWidgetHeader/DynamicWidgetHeader.cjs');
require('qrcode');
require('../../../../../../context/LoadingContext/LoadingContext.cjs');
require('i18next');
require('../../../../context/DynamicWidgetContext.cjs');
require('../../../../../../components/UserProfile/parts/UserProfileField/components/VerifiedEmailIcon/VerifiedEmailIcon.cjs');
require('formik');
require('../../../../../../components/IconButton/IconButton.cjs');
require('../../../../../../components/Alert/Alert.cjs');
require('@dynamic-labs/viem-utils');
require('../../../../views/ManagePasskeysWidgetView/PasskeyCard/PasskeyCard.cjs');
require('../../../../../../components/InlineWidget/InlineWidget.cjs');
require('../../../../../../components/MenuList/Dropdown/Dropdown.cjs');
require('../../../../../../components/Popper/Popper/Popper.cjs');
var PopperContext = require('../../../../../../components/Popper/PopperContext/PopperContext.cjs');
var Portal = require('../../../../../../components/Portal/Portal.cjs');

const DynamicWidgetModal = ({ children, isShown, onClose, zIndex, className, transitionEvents = {}, }) => {
    usePreventPageScroll.usePreventPageScroll(Boolean(isShown));
    return (jsxRuntime.jsx(Portal.Portal, Object.assign({ zIndex: zIndex, handleClose: () => onClose === null || onClose === void 0 ? void 0 : onClose(), isShown: isShown, withBackdrop: true }, transitionEvents, { children: jsxRuntime.jsx("div", { className: classNames.classNames('dynamic-widget-modal', className), children: jsxRuntime.jsx(PopperContext.PopperProvider, { children: children }) }) })));
};

exports.DynamicWidgetModal = DynamicWidgetModal;
