/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { AnalyticsVisitResponse } from '../models';
export interface GetVisitAnalyticsRequest {
    environmentId: string;
    startDate?: string;
    endDate?: string;
}
export interface GetWalletsBreakdownRequest {
    environmentId: string;
    startDate?: string;
    endDate?: string;
}
/**
 *
 */
export declare class AnalyticsApi extends runtime.BaseAPI {
    /**
     */
    getVisitAnalyticsRaw(requestParameters: GetVisitAnalyticsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<AnalyticsVisitResponse>>;
    /**
     */
    getVisitAnalytics(requestParameters: GetVisitAnalyticsRequest, initOverrides?: RequestInit): Promise<AnalyticsVisitResponse>;
    /**
     * Fetch visit analytics
     */
    getWalletsBreakdownRaw(requestParameters: GetWalletsBreakdownRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<object>>>;
    /**
     * Fetch visit analytics
     */
    getWalletsBreakdown(requestParameters: GetWalletsBreakdownRequest, initOverrides?: RequestInit): Promise<Array<object>>;
}
