/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { ChainToken } from '../models';
export interface GetAllTokensByChainIdRequest {
    chainId: string;
}
/**
 *
 */
export declare class ChainTokensApi extends runtime.BaseAPI {
    /**
     * Get all tokens for passed chainId.
     */
    getAllTokensByChainIdRaw(requestParameters: GetAllTokensByChainIdRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ChainToken>>>;
    /**
     * Get all tokens for passed chainId.
     */
    getAllTokensByChainId(requestParameters: GetAllTokensByChainIdRequest, initOverrides?: RequestInit): Promise<Array<ChainToken>>;
}
