/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { ChainalysisConfiguration } from '../models';
export interface DisableSanctionsApiByEnvironmentIdRequest {
    environmentId: string;
}
export interface EnableSanctionsApiByEnvironmentIdRequest {
    environmentId: string;
}
export interface GetChainalysisByEnvironmentIdRequest {
    environmentId: string;
}
/**
 *
 */
export declare class ChainalysisApi extends runtime.BaseAPI {
    /**
     * Disables the Sanctions API
     */
    disableSanctionsApiByEnvironmentIdRaw(requestParameters: DisableSanctionsApiByEnvironmentIdRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ChainalysisConfiguration>>;
    /**
     * Disables the Sanctions API
     */
    disableSanctionsApiByEnvironmentId(requestParameters: DisableSanctionsApiByEnvironmentIdRequest, initOverrides?: RequestInit): Promise<ChainalysisConfiguration>;
    /**
     * Enable the Sanctions API
     */
    enableSanctionsApiByEnvironmentIdRaw(requestParameters: EnableSanctionsApiByEnvironmentIdRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ChainalysisConfiguration>>;
    /**
     * Enable the Sanctions API
     */
    enableSanctionsApiByEnvironmentId(requestParameters: EnableSanctionsApiByEnvironmentIdRequest, initOverrides?: RequestInit): Promise<ChainalysisConfiguration>;
    /**
     * Find the Chainalysis configuration for an environment.
     */
    getChainalysisByEnvironmentIdRaw(requestParameters: GetChainalysisByEnvironmentIdRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ChainalysisConfiguration>>;
    /**
     * Find the Chainalysis configuration for an environment.
     */
    getChainalysisByEnvironmentId(requestParameters: GetChainalysisByEnvironmentIdRequest, initOverrides?: RequestInit): Promise<ChainalysisConfiguration>;
}
