/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { ChainEnum, ChainToken } from '../models';
export interface GetAllTokensByChainRequest {
    chainName: ChainEnum;
    networkId?: number;
}
/**
 *
 */
export declare class ChainsApi extends runtime.BaseAPI {
    /**
     * Get tokens for passed chainName.
     */
    getAllTokensByChainRaw(requestParameters: GetAllTokensByChainRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ChainToken>>>;
    /**
     * Get tokens for passed chainName.
     */
    getAllTokensByChain(requestParameters: GetAllTokensByChainRequest, initOverrides?: RequestInit): Promise<Array<ChainToken>>;
}
