/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { Event, EventType } from '../models';
export interface GetEventsRequest {
    environmentId: string;
    cursor?: string;
    resourceType?: string;
}
/**
 *
 */
export declare class EventsApi extends runtime.BaseAPI {
    /**
     * Get event types
     */
    getEventTypesRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<EventType>>>;
    /**
     * Get event types
     */
    getEventTypes(initOverrides?: RequestInit): Promise<Array<EventType>>;
    /**
     * Get environment events
     */
    getEventsRaw(requestParameters: GetEventsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Event>>>;
    /**
     * Get environment events
     */
    getEvents(requestParameters: GetEventsRequest, initOverrides?: RequestInit): Promise<Array<Event>>;
}
