/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { OrganizationMembersResponse } from '../models';
export interface DeleteMemberByIdRequest {
    memberId: string;
}
export interface GetOrganizationMembersRequest {
    organizationId: string;
}
/**
 *
 */
export declare class MembersApi extends runtime.BaseAPI {
    /**
     * Delete user membership from being an admin of an organization
     */
    deleteMemberByIdRaw(requestParameters: DeleteMemberByIdRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;
    /**
     * Delete user membership from being an admin of an organization
     */
    deleteMemberById(requestParameters: DeleteMemberByIdRequest, initOverrides?: RequestInit): Promise<void>;
    /**
     * Get all users that are admins for an organization
     */
    getOrganizationMembersRaw(requestParameters: GetOrganizationMembersRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<OrganizationMembersResponse>>;
    /**
     * Get all users that are admins for an organization
     */
    getOrganizationMembers(requestParameters: GetOrganizationMembersRequest, initOverrides?: RequestInit): Promise<OrganizationMembersResponse>;
}
