/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { SdkView, SdkViewType, SdkViewUpdateRequest, SdkViewsResponse } from '../models';
export interface GetSdkViewRequest {
    environmentId: string;
    sdkViewType: SdkViewType;
}
export interface GetSdkViewsRequest {
    environmentId: string;
}
export interface UpdateSdkViewRequest {
    environmentId: string;
    sdkViewType: SdkViewType;
    sdkViewUpdateRequest: SdkViewUpdateRequest;
}
/**
 *
 */
export declare class SDKViewsApi extends runtime.BaseAPI {
    /**
     * Get a sdk view given a type and environment
     */
    getSdkViewRaw(requestParameters: GetSdkViewRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SdkView>>;
    /**
     * Get a sdk view given a type and environment
     */
    getSdkView(requestParameters: GetSdkViewRequest, initOverrides?: RequestInit): Promise<SdkView>;
    /**
     * Get the sdk views for an environment
     */
    getSdkViewsRaw(requestParameters: GetSdkViewsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SdkViewsResponse>>;
    /**
     * Get the sdk views for an environment
     */
    getSdkViews(requestParameters: GetSdkViewsRequest, initOverrides?: RequestInit): Promise<SdkViewsResponse>;
    /**
     * Updates the configs for the sdk view and project environment
     */
    updateSdkViewRaw(requestParameters: UpdateSdkViewRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<SdkView>>;
    /**
     * Updates the configs for the sdk view and project environment
     */
    updateSdkView(requestParameters: UpdateSdkViewRequest, initOverrides?: RequestInit): Promise<SdkView>;
}
