/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { Session } from '../models';
export interface RevokeSessionByIdRequest {
    sessionId: string;
}
/**
 *
 */
export declare class SessionsApi extends runtime.BaseAPI {
    /**
     * Revoke a session
     */
    revokeSessionByIdRaw(requestParameters: RevokeSessionByIdRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Session>>;
    /**
     * Revoke a session
     */
    revokeSessionById(requestParameters: RevokeSessionByIdRequest, initOverrides?: RequestInit): Promise<Session>;
}
