/**
 * Dashboard API
 * Dashboard API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import * as runtime from '../runtime';
import { InternalUserFields, UserResponse, UserSearchFilterParams, UsersResponse } from '../models';
export interface CreateUserRequest {
    environmentId: string;
    internalUserFields: InternalUserFields;
}
export interface DeleteUserRequest {
    userId: string;
}
export interface GetEnvironmentUsersRequest {
    environmentId: string;
    filter?: UserSearchFilterParams;
    orderBy?: string;
    offset?: number;
    limit?: number;
}
export interface GetUserRequest {
    userId: string;
}
export interface UpdateUserRequest {
    userId: string;
    internalUserFields: InternalUserFields;
}
/**
 *
 */
export declare class UsersApi extends runtime.BaseAPI {
    /**
     * Creates a new user
     */
    createUserRaw(requestParameters: CreateUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<UserResponse>>;
    /**
     * Creates a new user
     */
    createUser(requestParameters: CreateUserRequest, initOverrides?: RequestInit): Promise<UserResponse>;
    /**
     * Delete user
     */
    deleteUserRaw(requestParameters: DeleteUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;
    /**
     * Delete user
     */
    deleteUser(requestParameters: DeleteUserRequest, initOverrides?: RequestInit): Promise<void>;
    /**
     * Get all users for an environment
     */
    getEnvironmentUsersRaw(requestParameters: GetEnvironmentUsersRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<UsersResponse>>;
    /**
     * Get all users for an environment
     */
    getEnvironmentUsers(requestParameters: GetEnvironmentUsersRequest, initOverrides?: RequestInit): Promise<UsersResponse>;
    /**
     * Get a user by Id
     */
    getUserRaw(requestParameters: GetUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<UserResponse>>;
    /**
     * Get a user by Id
     */
    getUser(requestParameters: GetUserRequest, initOverrides?: RequestInit): Promise<UserResponse>;
    /**
     * Update a user
     */
    updateUserRaw(requestParameters: UpdateUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<UserResponse>>;
    /**
     * Update a user
     */
    updateUser(requestParameters: UpdateUserRequest, initOverrides?: RequestInit): Promise<UserResponse>;
}
